delete from cohort_detail;
delete from cohort;
delete from corp_member;
delete from mtld;
delete from school;
delete from tfa_user;
delete from criteria;
delete from criteria_category;
delete from region;
COMMIT;
