
CREATE TABLE stagmtld 
(
    PLACEMENT_ADVISOR_TFA_UID     VARCHAR2(255 CHAR),
    FIRST_NAME                     VARCHAR2(255 CHAR),
    LAST_NAME                     VARCHAR2(255 CHAR),
	REGION_CODE                     VARCHAR2(255 CHAR)
);

CREATE TABLE stagcm 
(
    FIRST_NAME              VARCHAR2(255 CHAR),
    LAST_NAME               VARCHAR2(255 CHAR),
    TFA_MASTER_UID          VARCHAR2(255 CHAR),
    SCHOOL_TFA_UID          VARCHAR2(255 CHAR),
    PREVIOUS_ADVISOR_ID 	VARCHAR2(255 CHAR),
    ETHNICITY               VARCHAR2(255 CHAR),
	REGION_CODE             VARCHAR2(255 CHAR),
	PLACEMENT_STATUS		VARCHAR2(255 CHAR),
    CORPS_YEARS             NUMBER
);

CREATE TABLE stagregion
(
  REGION_CODE     VARCHAR2(255 CHAR),
  REGION_NAME     VARCHAR2(255 CHAR)
);

CREATE TABLE stagschool
(
  ADDRESS         VARCHAR2(500 CHAR),
  CITY            VARCHAR2(200 CHAR),
  COUNTRY         VARCHAR2(200 CHAR),
  STATE           VARCHAR2(200 CHAR),
  ZIP             VARCHAR2(200 CHAR),
  DISTRICT        VARCHAR2(200 CHAR),
  NAME            VARCHAR2(200 CHAR),
  TYPE            VARCHAR2(200 CHAR),
  REGION_CODE     VARCHAR2(255 CHAR),
  SCHOOL_TFA_UID  VARCHAR2(200 CHAR),
  TFASCHOOLID	  VARCHAR2(200 CHAR)
);